Q) Use the SVD from Fig. 11.7. Suppose Leslie Assigns rating 3 to Alien and rating 4 to titanic, giving us a representation of Lesliein "movie space" of [0,3,0,0,4].Find the representation of Leslie in concept space. What does that representation predict about howwell leslie would like the other movies appearing in our example data?

In [38]:
# Pritam shrestha
# DSC550 - Data Mining
# Date: 07/26/2020
# Problem:11.3.2
# References: http://orion.towson.edu/~mzimand/ainternetalg/Sol-Assign_10.pdf and Mining of Massive Datasets.
              

In [39]:
import numpy as np
from scipy.linalg import svd

# the given vectors form figure.
M=np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,0,0,4,4],[0,0,0,5,5],[0,0,0,2,2]])
M

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 0, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 0, 0, 2, 2]])

In [40]:
# from given fig
U=np.array([[.14,0],[.42,0],[.56,0],[.70,0],[0,.60],[0,.75],[0,.30]])
U

array([[0.14, 0.  ],
       [0.42, 0.  ],
       [0.56, 0.  ],
       [0.7 , 0.  ],
       [0.  , 0.6 ],
       [0.  , 0.75],
       [0.  , 0.3 ]])

In [41]:
# from given fig
sigma=np.array([[12.4,0],[0,9.5]])
sigma

array([[12.4,  0. ],
       [ 0. ,  9.5]])

In [42]:
# from given fig
VT=np.array([[.58,.58,.58,0,0],[0,0,0,.71,.71]])
VT

array([[0.58, 0.58, 0.58, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.71, 0.71]])

In [43]:
# Leslie movie space
Leslie=np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,0,0,4,4],[0,0,0,5,5],[0,0,0,2,2],[0,3,0,0,4]])
Leslie

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 0, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 0, 0, 2, 2],
       [0, 3, 0, 0, 4]])

In [23]:
Leslie_space=np.array([0,3,0,0,4])

In [44]:
# now calculating other rating using movie space
rating=np.dot(Leslie_space,VT.T)
rating

array([1.74, 2.84])

In [48]:
# for other movies.
other_movies=np.dot(rating,VT)
print(other_movies)

[1.0092 1.0092 1.0092 2.0164 2.0164]


In [51]:
# From above result, she likes romantic movie silghtly more than others.
# Thanks!!!