b) The first five attributes are Boolean, and the last is an integer "rating." Assume that the scale factor for the rating is α. Compute, as a function of α, the cosine distances between each pair of profiles. For each of α = 0, 0.5, 1, and 2, determine the cosine of the angle between each pair of vectors.

In [15]:
# Pritam shrestha
# DSC550 - Data Mining
# Date: 07/22/2020
# Problem:1(B,C,D,E,F)

In [7]:
# creating function to calculate cosine distance
def cosDist(x,y):
    return np.dot(x,y) / (np.sqrt(np.sum(np.power(x,2))) * np.sqrt(np.sum(np.power(y,2))))

In [8]:
import pandas as pd
import numpy as np

# defining function to calculate weighted _cosine_dist
def calculate_weighted_cosine_dist(colIndex,alpha):
    p=[[1,0,1,0,1,2],[1,1,0,0,1,6],[0,1,0,1,0,2]]
    o=pd.DataFrame(p,columns=None)
    # Transform of o matrix
    m=o.T
    # adding columns for m matrix
    m.columns=['A','B','C']
    data=m.T
    data[colIndex]=data[colIndex] * alpha
    print(cosDist(data.loc['A'], data.loc['B']))
    print(cosDist(data.loc['B'], data.loc['C']))
    print(cosDist(data.loc['A'], data.loc['C']))
    print("Weighted value:")
    print(data[colIndex])


In [64]:
# weighted index=5
# for alpha=0
calculate_weighted_cosine_dist(5,0)

0.6666666666666667
0.40824829046386296
0.0
Weighted value:
A    0
B    0
C    0
Name: 5, dtype: int64


In [65]:
# for alpha=0.5
calculate_weighted_cosine_dist(5,0.5)

0.7216878364870323
0.6666666666666667
0.2886751345948129
Weighted value:
A    1.0
B    3.0
C    1.0
Name: 5, dtype: float64


In [66]:
# for alpha=1
calculate_weighted_cosine_dist(5,1)

0.8473185457363233
0.8498365855987975
0.6172133998483676
Weighted value:
A    2
B    6
C    2
Name: 5, dtype: int64


In [67]:
# for alpha=2
calculate_weighted_cosine_dist(5,2)

0.9460945407607455
0.9525793444156805
0.8651809126974003
Weighted value:
A     4
B    12
C     4
Name: 5, dtype: int64


In [68]:
# Thanks!!!

c)"...There are many options for the second column ⟨x, y, z⟩. Write down those constraints on x, y, and z. Then, identify in the list below the one column that could be ⟨x, y, z⟩. "

There is no list. So, please construct an orthonormal vector and show your work on how you computed it. There are infinitively many, so don't worry if you have a slightly different answer than one of your classmates.

In [69]:
# let orthogola vector is
o_v=np.array([1,1,-1])


In [60]:
# hence the col_v is
col_v=np.array([1,1,2])

In [62]:
# checking condition
result2=np.dot(col_v,o_v)
result

0

In [63]:
# Hence, proved and final vector is col_v is
col_v

array([1, 1, 2])

In [ ]:
# Thanks!!!

d)Suppose we have three points in a two dimensional space: (1,1), (2,2), and (3,4). We want to perform PCA on these points, so we construct a 2-by-2 matrix whose eigenvectors are the directions that best represent these three points. Construct this matrix.

In [26]:
# finding best eigenvectors.
import scipy.linalg as la
V = np.array([[1,1],[2,2],[3,4]])
print(V)


[[1 1]
 [2 2]
 [3 4]]


In [27]:
# for eigenvalue and vectors
V1 = np.dot(V.transpose(),V)
print(V1)

[[14 17]
 [17 21]]


In [30]:
# evaluating 2x2 matrix
eigenvalue,eigenvector=la.eig(V1)
eigenvector

array([[-0.77512996, -0.63180182],
       [ 0.63180182, -0.77512996]])

In [ ]:
# Thanks!!!

E)Identify the vector that is orthogonal to the vector [1,2,3].

In [59]:
# Theory: dot product of two orthogoal vector is always 0.
# given vector
v=np.array([1,2,3])

In [48]:
# checking 
v=np.array([1,2,3])

v1=np.array([1,1,-1])
result=np.dot(v1,v)
print(result)

0


In [70]:
# changing into dataframe
M = pd.DataFrame(np.array([[1, 0, 0], [0, 2, 0], [0, 0, 0]]))
# Reference https://numpy.org/doc/stable/reference/generated/numpy.linalg.pinv.html
result1=np.linalg.pinv(M)
print(result1)

[[1.  0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0. ]]


In [52]:
# Thanks!!