Modify the training set of fig.12.6 so that example b also includes the word "nigeria". Find a wight vector that separates
the positive and negative examples, using 
c) The basic method with a variable threshold, as suggested in section 12.2.4.
d) The winnow method with a variable threshold, as suggested in section 12.2.4.

In [45]:
# Pritam shrestha
# DSC550 - Data Mining
# Date: 07/08/2020
# Problem:12.2.1
# Reference:peer code and book exercise


# Importing important libraries
import numpy as np
import traceback

def Using_basic_algo(given_Matrix, l_rate):
   

    # initial value of w_matrix
    w_matrix = [0, 0, 0, 0, 0, 0]
    for i in range(len(given_Matrix)):
        print()
        print('Iteration :', i+1)
        print('older value of W : ', w_matrix)
        w = np.sum(w_matrix*given_Matrix[i][:-1])
        print('w.x = ', w)
        if w == 0:
            w_matrix = w_matrix + l_rate*given_Matrix[i][-1]*given_Matrix[i][:-1]
        elif w > 0 and given_Matrix[i][-1] == -1:
            w_matrix = w_matrix + l_rate*given_Matrix[i][-1]*given_Matrix[i][:-1]
        elif w < 0 and given_Matrix[i][-1] == +1:
            continue
        print('new value of W: ', w_matrix)
    return


if __name__ == '__main__':

    # Given data
    given_values = {'a': (1, 1, 0, 1, 1, -1, +1), 'b': (0, 0, 1, 1, 1, -1, -1), 'c': (0, 1, 1, 0, 0, -1, +1),
             'd': (1, 0, 0, 1, 0, -1, -1), 'e': (1, 0, 1, 0, 1, -1, +1), 'f': (1, 0, 1, 1, 0, -1, -1)}

    # Converting into Matrix
    heading = ['a', 'b', 'c', 'd', 'e', 'f']
    given_Matrix = np.array([given_values[i] for i in heading])


    # Lets use learning rate as 0.5
    l_rate = 0.5

    try:
        # Apply basic method
        Using_basic_algo(given_Matrix, l_rate)
    except Exception as exception:
        print('exception')
        traceback.print_exc()
        print('An exception of type {0} occurred. Arguments:\n{1!r}'.format(type(exception).__name__, exception.args))
    finally:
        print("Finally block is executed whether exception is handled or not!!")



Iteration : 1
older value of W :  [0, 0, 0, 0, 0, 0]
w.x =  0
new value of W:  [ 0.5  0.5  0.   0.5  0.5 -0.5]

Iteration : 2
older value of W :  [ 0.5  0.5  0.   0.5  0.5 -0.5]
w.x =  1.5
new value of W:  [ 0.5  0.5 -0.5  0.   0.   0. ]

Iteration : 3
older value of W :  [ 0.5  0.5 -0.5  0.   0.   0. ]
w.x =  0.0
new value of W:  [ 0.5  1.   0.   0.   0.  -0.5]

Iteration : 4
older value of W :  [ 0.5  1.   0.   0.   0.  -0.5]
w.x =  1.0
new value of W:  [ 0.   1.   0.  -0.5  0.   0. ]

Iteration : 5
older value of W :  [ 0.   1.   0.  -0.5  0.   0. ]
w.x =  0.0
new value of W:  [ 0.5  1.   0.5 -0.5  0.5 -0.5]

Iteration : 6
older value of W :  [ 0.5  1.   0.5 -0.5  0.5 -0.5]
w.x =  1.0
new value of W:  [ 0.   1.   0.  -1.   0.5  0. ]
Finally block is executed whether exception is handled or not!!


In [48]:
import numpy as np
import traceback


def eval_w(w, X, act):
    j = 0
    if act == 'viagra':
        for b in X:
            if b == 1:
                w[j] = w[j] * 2
            j += 1
    elif act == 'nigeria':
        for b in X:
            if b == 1:
                w[j] = w[j] / 2
            j += 1

    return w


def winnow(value_M):
   
    # initialize w
    w = [1, 1, 1, 1, 1, 1]
    iteration = 0
    w_diff = 0
    while w_diff < 2 and iteration < 20:
        wso = sum(w[:5])
        for i in range(len(value_M)):
            wi = sum(w * value_M[i][:-1])
            if wi > 0 and value_M[i][-1] == -1:
                # eval weight
                w = eval_w(w, value_M[i][:-2], act='viagra')
                w[-1] = w[-1] * 2
            elif (wi < 0 and value_M[i][-1] == 1) or wi == 0:
                # eval weight
                w = eval_w(w, value_M[i][:-2], act='nigeria')
                w[-1] = w[-1] / 2
        wsn = sum(w[:5])
        w_diff = wsn - wso
        iteration += 1

    return iteration, w


if __name__ == '__main__':

    # Given data
    given_values = {'a': (1, 1, 0, 1, 1, -1, +1), 'b': (0, 0, 1, 1, 1, -1, -1), 'c': (0, 1, 1, 0, 0, -1, +1),
             'd': (1, 0, 0, 1, 0, -1, -1), 'e': (1, 0, 1, 0, 1, -1, +1), 'f': (1, 0, 1, 1, 0, -1, -1)}

    # Convert to Matrix
    heading = ['a', 'b', 'c', 'd', 'e', 'f']
    value_M = np.array([given_values[i] for i in heading])

    # Display matrix
    print(value_M)

    try:
        # Apply winnow method
        iteration, w = winnow(value_M)
        print('Iteration Count: ', iteration)
        print('Final weight:', w[:5])
    except Exception as exception:
        print('exception')
        traceback.print_exc()
        print('An exception of type {0} occurred. Arguments:\n{1!r}'.format(type(exception).__name__, exception.args))
    finally:
        print("Finally block is executed whether exception is handled or not!!")

[[ 1  1  0  1  1 -1  1]
 [ 0  0  1  1  1 -1 -1]
 [ 0  1  1  0  0 -1  1]
 [ 1  0  0  1  0 -1 -1]
 [ 1  0  1  0  1 -1  1]
 [ 1  0  1  1  0 -1 -1]]
Iteration Count:  1
Final weight: [4, 1, 4, 8, 2]
Finally block is executed whether exception is handled or not!!


In [33]:
# Thanks!!!